//! IEEE OUI vendor table — loads the binary blob generated by
//! `tools/gen_oui.py` from https://standards-oui.ieee.org/oui/oui.csv (IEEE
//! Registration Authority, MA-L assignments). Do not edit `oui.bin` by hand;
//! regenerate it with `python tools/gen_oui.py`.
//!
//! Blob format (little-endian):
//!   b"OUI1"                        4-byte magic
//!   u32 n_prefixes, u32 n_vendors  header counts
//!   n_prefixes x u32               sorted 24-bit OUI prefixes
//!   n_prefixes x u16               vendor index, parallel to the above
//!   u32 total_len                  byte length of the string table
//!   total_len bytes                UTF-8 vendor names, concatenated
//!   n_vendors x u32                start offset of each name (end = next
//!                                  start, or total_len for the last vendor)
//!
//! Vendor names are normalised by the generator: corporate suffixes dropped,
//! title-cased, 24 characters at most.

use std::sync::OnceLock;

static BLOB: &[u8] = include_bytes!("oui.bin");

struct Table {
    prefixes: &'static [u8],
    vendor_idx: &'static [u8],
    strings: &'static [u8],
    offsets: &'static [u8],
    n_prefixes: usize,
    n_vendors: usize,
}

fn read_u32(bytes: &[u8], i: usize) -> Option<u32> {
    Some(u32::from_le_bytes(bytes.get(i * 4..i * 4 + 4)?.try_into().ok()?))
}

fn read_u16(bytes: &[u8], i: usize) -> Option<u16> {
    Some(u16::from_le_bytes(bytes.get(i * 2..i * 2 + 2)?.try_into().ok()?))
}

/// Parse and validate the blob; a malformed or truncated blob yields `None`
/// rather than panicking.
fn parse(blob: &'static [u8]) -> Option<Table> {
    if blob.len() < 12 || &blob[0..4] != b"OUI1" {
        return None;
    }
    let n_prefixes = u32::from_le_bytes(blob[4..8].try_into().ok()?) as usize;
    let n_vendors = u32::from_le_bytes(blob[8..12].try_into().ok()?) as usize;

    let mut pos = 12usize;
    let prefixes = blob.get(pos..pos + n_prefixes.checked_mul(4)?)?;
    pos += prefixes.len();
    let vendor_idx = blob.get(pos..pos + n_prefixes.checked_mul(2)?)?;
    pos += vendor_idx.len();
    let total_len = read_u32(blob.get(pos..pos + 4)?, 0)? as usize;
    pos += 4;
    let strings = blob.get(pos..pos + total_len)?;
    pos += strings.len();
    let offsets = blob.get(pos..pos + n_vendors.checked_mul(4)?)?;

    Some(Table { prefixes, vendor_idx, strings, offsets, n_prefixes, n_vendors })
}

impl Table {
    fn prefix_at(&self, i: usize) -> Option<u32> {
        read_u32(self.prefixes, i)
    }

    /// Binary search for `target` among the sorted prefixes; `Ok(i)` names
    /// index `i` into `vendor_idx`.
    fn find(&self, target: u32) -> Option<usize> {
        let (mut lo, mut hi) = (0usize, self.n_prefixes);
        while lo < hi {
            let mid = lo + (hi - lo) / 2;
            match self.prefix_at(mid)?.cmp(&target) {
                std::cmp::Ordering::Less => lo = mid + 1,
                std::cmp::Ordering::Greater => hi = mid,
                std::cmp::Ordering::Equal => return Some(mid),
            }
        }
        None
    }

    fn vendor_name(&self, vendor_i: usize) -> Option<&'static str> {
        if vendor_i >= self.n_vendors {
            return None;
        }
        let start = read_u32(self.offsets, vendor_i)? as usize;
        let end = if vendor_i + 1 < self.n_vendors {
            read_u32(self.offsets, vendor_i + 1)? as usize
        } else {
            self.strings.len()
        };
        std::str::from_utf8(self.strings.get(start..end)?).ok()
    }
}

static TABLE: OnceLock<Option<Table>> = OnceLock::new();

/// The vendor that owns a MAC, matched on its first three bytes.
pub fn vendor(mac: &[u8; 6]) -> Option<&'static str> {
    let table = TABLE.get_or_init(|| parse(BLOB)).as_ref()?;
    let prefix = u32::from_be_bytes([0, mac[0], mac[1], mac[2]]);
    let i = table.find(prefix)?;
    let vendor_i = read_u16(table.vendor_idx, i)? as usize;
    table.vendor_name(vendor_i)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn truncated_blob_returns_none_never_panics() {
        assert!(parse(&BLOB[..11]).is_none(), "too short for even the header");
        assert!(parse(&BLOB[..BLOB.len() - 1]).is_none(), "missing the last offset byte");
        assert!(parse(b"NOPE________").is_none(), "wrong magic");
        assert!(vendor(&[0, 0, 0, 0, 0, 0]).is_some(), "the real BLOB still resolves");
    }

    #[test]
    fn header_prefix_count_matches_the_slice() {
        let table = parse(BLOB).expect("real blob parses");
        assert_eq!(table.prefixes.len(), table.n_prefixes * 4);
        assert_eq!(table.vendor_idx.len(), table.n_prefixes * 2);
    }

    #[test]
    fn first_and_last_prefix_are_ascending() {
        let table = parse(BLOB).expect("real blob parses");
        let first = table.prefix_at(0).expect("first prefix reads");
        let last = table.prefix_at(table.n_prefixes - 1).expect("last prefix reads");
        assert!(first < last, "table must be sorted ascending");
    }
}
