#!/usr/bin/env python3
"""Generate src/ui/landmask.rs from Natural Earth 1:110m land polygons.

Data: Natural Earth (naturalearthdata.com), public domain, via the
natural-earth-vector GeoJSON mirror. Run once; the generated file is committed.

    python tools/gen_landmask.py
"""
import json
import math
import os
import sys
import urllib.request

URL = "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_land.geojson"
W, H = 360, 180
OUT = os.path.join(os.path.dirname(__file__), "..", "src", "ui", "landmask.rs")


def rings(geom):
    """All linear rings of a Polygon/MultiPolygon, grouped per polygon."""
    t = geom["type"]
    if t == "Polygon":
        yield geom["coordinates"]
    elif t == "MultiPolygon":
        for poly in geom["coordinates"]:
            yield poly


def inside(rs, x, y):
    """Even-odd ray casting over every ring of one polygon (holes included)."""
    hit = False
    for ring in rs:
        n = len(ring)
        for i in range(n):
            x1, y1 = ring[i][0], ring[i][1]
            x2, y2 = ring[(i + 1) % n][0], ring[(i + 1) % n][1]
            if (y1 > y) != (y2 > y):
                xi = x1 + (y - y1) * (x2 - x1) / (y2 - y1)
                if x < xi:
                    hit = not hit
    return hit


def main():
    print("downloading", URL)
    with urllib.request.urlopen(URL, timeout=120) as r:
        gj = json.loads(r.read().decode("utf-8"))

    grid = bytearray(W * H // 8)
    polys = [rs for f in gj["features"] for rs in rings(f["geometry"])]
    print(f"{len(polys)} polygons")

    for rs in polys:
        xs = [p[0] for ring in rs for p in ring]
        ys = [p[1] for ring in rs for p in ring]
        c0 = max(0, int(math.floor(min(xs) + 180.0)))
        c1 = min(W - 1, int(math.floor(max(xs) + 180.0)))
        r0 = max(0, int(math.floor(90.0 - max(ys))))
        r1 = min(H - 1, int(math.floor(90.0 - min(ys))))
        for row in range(r0, r1 + 1):
            lat = 89.5 - row
            for col in range(c0, c1 + 1):
                idx = row * W + col
                if grid[idx >> 3] >> (idx & 7) & 1:
                    continue
                if inside(rs, col - 179.5, lat):
                    grid[idx >> 3] |= 1 << (idx & 7)

    land = sum(bin(b).count("1") for b in grid)
    print(f"{land} land cells of {W * H} ({100.0 * land / (W * H):.1f}%)")

    body = ",\n    ".join(
        ", ".join(f"0x{b:02x}" for b in grid[i:i + 16]) for i in range(0, len(grid), 16)
    )
    src = f'''//! 1° land/water mask of the Earth, generated by `tools/gen_landmask.py`.
//!
//! Source: Natural Earth 1:110m land polygons — Natural Earth, public domain.
//! Row-major, {W}×{H} cells, row 0 = 90°N, column 0 = 180°W; a set bit is land.
//! Do not edit by hand; re-run the script to regenerate.

pub const W: usize = {W};
pub const H: usize = {H};

pub static LAND: [u8; {W} * {H} / 8] = [
    {body},
];

/// `true` when the 1° cell containing this coordinate is land.
pub fn is_land(lat: f64, lon: f64) -> bool {{
    if !lat.is_finite() || !lon.is_finite() {{
        return false;
    }}
    let row = (90.0 - lat).floor().clamp(0.0, (H - 1) as f64) as usize;
    let col = (lon + 180.0).rem_euclid(360.0).floor() as usize % W;
    let idx = row * W + col;
    LAND[idx >> 3] >> (idx & 7) & 1 == 1
}}
'''
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(src)
    print("wrote", os.path.abspath(OUT))


if __name__ == "__main__":
    sys.exit(main())
