#!/usr/bin/env python3
"""Generate src/ui/oui_table.rs from the IEEE MA-L (OUI) registry.

Data: IEEE Registration Authority, https://standards-oui.ieee.org/oui/oui.csv
(the Wireshark `manuf` list is the fallback if the IEEE site refuses the
request). Run once; the generated file is committed.

    python tools/gen_oui.py

The output is three parallel statics — a sorted &[u32] of 24-bit prefixes, a
&[u16] index into a deduplicated &[&str] vendor table — plus a binary-search
`vendor()`. Roughly 35k prefixes, a few hundred KB of source.
"""
import csv
import io
import os
import re
import sys
import urllib.request
from datetime import date

IEEE = "https://standards-oui.ieee.org/oui/oui.csv"
WIRESHARK = "https://raw.githubusercontent.com/wireshark/wireshark/master/manuf"
OUT = os.path.join(os.path.dirname(__file__), "..", "src", "ui", "oui_table.rs")
MAX_LEN = 24
UA = {"User-Agent": "Mozilla/5.0 (pipboy oui table generator)"}

# Corporate noise at the end of a name. "Electronics" is deliberately absent:
# "Samsung Electronics Co.,Ltd" should keep it.
SUFFIXES = {
    "inc", "incorporated", "llc", "llp", "ltd", "limited", "co", "corp",
    "corporation", "company", "gmbh", "mbh", "ag", "sa", "sas", "sarl", "srl",
    "bv", "nv", "plc", "pty", "oy", "oyj", "ab", "as", "a/s", "kg", "kft",
    "spa", "zrt", "kk", "pte", "sdn", "bhd", "cv", "ug", "technologies",
    "technology", "the",
}


def fetch(url):
    req = urllib.request.Request(url, headers=UA)
    with urllib.request.urlopen(req, timeout=120) as r:
        return r.read().decode("utf-8", "replace")


def from_ieee(text):
    for row in csv.DictReader(io.StringIO(text)):
        asn = (row.get("Assignment") or "").strip()
        org = (row.get("Organization Name") or "").strip()
        if len(asn) == 6 and org:
            yield asn.upper(), org


def from_wireshark(text):
    for line in text.splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split("\t")
        mac = parts[0].strip()
        if "/" in mac:  # 28/36-bit block, not an OUI
            continue
        hexs = mac.replace(":", "").replace("-", "").upper()
        if len(hexs) != 6:
            continue
        # Column 2 is the short name, column 3 (when present) the long one.
        org = (parts[2] if len(parts) > 2 and parts[2].strip() else parts[1]).strip()
        if org:
            yield hexs, org


def titlecase(word):
    """Title-case a word, leaving short all-caps acronyms (HP, AVM) alone."""
    return "-".join(
        p if p.isupper() and len(p) <= 3 else p.capitalize() for p in word.split("-")
    )


def normalise(org):
    """"Apple, Inc." -> "Apple"; "Espressif Inc." -> "Espressif"."""
    org = re.sub(r"[(\[].*?[)\]]", " ", org)          # drop parentheticals
    org = re.sub(r"[,;.]+", " ", org)                 # "Co.,Ltd" -> "Co Ltd"
    org = org.replace('"', "").replace("\\", "").replace("�", "")
    words = [w for w in re.split(r"\s+", org) if w]
    while words and re.sub(r"[^a-z/]", "", words[-1].lower()) in SUFFIXES:
        words.pop()
    words = [titlecase(w) for w in words if w]
    name = " ".join(words).strip()
    if len(name) > MAX_LEN:  # trim on a word boundary where one is near enough
        cut = name[:MAX_LEN].rstrip()
        space = cut.rfind(" ")
        name = cut[:space] if space >= MAX_LEN - 8 else cut
    return name


def main():
    table, source = {}, None
    for url, parse in ((IEEE, from_ieee), (WIRESHARK, from_wireshark)):
        try:
            rows = list(parse(fetch(url)))
        except Exception as e:  # noqa: BLE001 - any failure means "try the next one"
            print(f"{url}: {e}", file=sys.stderr)
            continue
        if len(rows) > 1000:
            table, source = dict(rows), url
            break
    if not table:
        sys.exit("no usable OUI source")

    vendors, index, prefixes = [], {}, []
    for hexs, org in sorted(table.items()):
        name = normalise(org)
        if not name:
            continue
        if name not in index:
            index[name] = len(vendors)
            vendors.append(name)
        prefixes.append((int(hexs, 16), index[name]))
    if len(vendors) > 0xFFFF:
        sys.exit(f"{len(vendors)} vendors do not fit a u16 index")

    def quoted(v):
        return '"' + v.replace("\\", "\\\\").replace('"', '\\"') + '",'

    def block(values, fmt, per_line):
        out = []
        for i in range(0, len(values), per_line):
            out.append("    " + " ".join(fmt(v) for v in values[i:i + per_line]))
        return "\n".join(out)

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(f'''//! IEEE OUI vendor table — generated by `tools/gen_oui.py`, do not edit by hand.
//!
//! Source: {source}
//! (IEEE Registration Authority, MA-L assignments), retrieved {date.today()}.
//! {len(prefixes)} prefixes, {len(vendors)} vendor names. Vendor names are
//! normalised: corporate suffixes dropped, title-cased, {MAX_LEN} characters at most.

/// Sorted 24-bit OUI prefixes; `VENDOR_IDX[i]` names `PREFIXES[i]`.
static PREFIXES: &[u32] = &[
{block([p for p, _ in prefixes], lambda v: f"0x{v:06x},", 10)}
];

/// Index into [`VENDORS`], parallel to [`PREFIXES`].
static VENDOR_IDX: &[u16] = &[
{block([i for _, i in prefixes], lambda v: f"{v},", 16)}
];

/// Deduplicated vendor names.
static VENDORS: &[&str] = &[
{block(vendors, quoted, 4)}
];

/// The vendor that owns a MAC, matched on its first three bytes.
pub fn vendor(mac: &[u8; 6]) -> Option<&'static str> {{
    let prefix = u32::from_be_bytes([0, mac[0], mac[1], mac[2]]);
    let i = PREFIXES.binary_search(&prefix).ok()?;
    VENDORS.get(*VENDOR_IDX.get(i)? as usize).copied()
}}
''')
    print(f"{OUT}: {len(prefixes)} prefixes, {len(vendors)} vendors, from {source}")


if __name__ == "__main__":
    main()
